name: bias_identifaction_tool
dependencies:
    - cherrypy=18.5.0
    - flask=1.1.1
    - pip
    - mongoengine=0.19.1
    - openpyxl=3.0.3
    - pillow=7.0.0
    - pymongo=3.10.1
    - numpy=1.18.1
    - scipy=1.4.1
    - matplotlib=3.2.1
    - h5py=2.10.0
    - networkx=2.4
    - gym=0.17.1
    - opencv=4.2.0
    - nltk=3.4
    - spyder-kernels >= 1.9.1
    - scikit-learn >=0.23.1
    - pandas=1.1.0
    - tqdm=4.48.2
    - cvxpy=1.1.3
    - pip:
        - grapheme==0.6.0
        - aif360==0.3.0
